### PR TITLE
Add Configuation for OBS Studio

### PR DESCRIPTION
**Pull request by fz20181223luogu**
As discussed in the meeting, we uploaded our OBS Studio configuation for the automation of production deployment.

### CODE REVIEW

**Review by ATATC — COMMENTED** [review]
@fz20181223luogu What are these window captures for?

**Comment by ATATC** [comment]
@qmascarenhas Please ask Jerry to post a preview of the configuration here.

**Comment by qmascarenhas** [comment]
> @qmascarenhas Please ask Jerry to post a preview of the configuration here.

@fz20181223luogu see Terry's request above. Can you please upload the OBS config file for the finalized camera settings please. A screen shot of the configuration might be helpful too.

**Comment by fz20181223luogu** [comment]
Currently I do not have any cameras connected so I can only post how the virtual camera layout would be without cameras
obs-layout
[obs-config.json](https://github.com/ProjectNeura/LEADS/files/15242755/obs-config.json)

**Pull request merged**
